api_platform:
    title: 'GANBAN'
    description: 'A Symfony API to manage project.'
    version: '1.0.0'
    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths: ['%kernel.project_dir%/src/Entity']

    # The list of enabled patch formats. The first one will be the default.
    patch_formats:
      json: ['application/merge-patch+json']

    swagger:
    # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
      versions: [3]
      api_keys:
        apiKey:
          name: Authorization
          type: header